<?php

namespace Database\Seeders;

use App\Models\Education;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EducationSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        $users = User::where('role', 'user')->get();

        $educations = [
            // ===== PROGRAMMING (10) =====
            [
                'title'       => 'freeCodeCamp — Belajar Coding Gratis',
                'description' => 'Platform belajar coding interaktif dengan ribuan jam content gratis. Dapatkan sertifikat setelah menyelesaikan kurikulum web development, data science, dan machine learning.',
                'url'         => 'https://www.freecodecamp.org',
                'category'    => 'programming',
                'level'       => 'basic',
                'views'       => 15420,
                'thumbnail'   => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'The Odin Project — Full Stack Curriculum',
                'description' => 'Kurikulum full-stack web development gratis dan open-source. Belajar HTML, CSS, JavaScript, Ruby on Rails, dan Node.js dengan project-based learning.',
                'url'         => 'https://www.theodinproject.com',
                'category'    => 'programming',
                'level'       => 'basic',
                'views'       => 12830,
                'thumbnail'   => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Laravel Official Documentation',
                'description' => 'Dokumentasi resmi framework Laravel. Panduan lengkap untuk membangun aplikasi web modern dengan PHP dari dasar sampai advanced.',
                'url'         => 'https://laravel.com/docs',
                'category'    => 'programming',
                'level'       => 'intermediate',
                'views'       => 9750,
                'thumbnail'   => 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'CS50 Harvard — Introduction to Computer Science',
                'description' => 'Kursus pengantar ilmu komputer dari Harvard University. Gratis di edX. Materi mencakup C, Python, SQL, dan web development.',
                'url'         => 'https://cs50.harvard.edu/x',
                'category'    => 'programming',
                'level'       => 'basic',
                'views'       => 18200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'JavaScript.info — Modern JavaScript Tutorial',
                'description' => 'Tutorial JavaScript dari dasar sampai advanced. Mencakup DOM, async, OOP, dan topik modern JavaScript yang komprehensif.',
                'url'         => 'https://javascript.info',
                'category'    => 'programming',
                'level'       => 'intermediate',
                'views'       => 8900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Codecademy — Learn Python 3',
                'description' => 'Kursus interaktif Python gratis dari Codecademy. Cocok untuk pemula dengan exercises langsung di browser.',
                'url'         => 'https://www.codecademy.com/learn/learn-python-3',
                'category'    => 'programming',
                'level'       => 'basic',
                'views'       => 11300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Exercism — Code Practice & Mentoring',
                'description' => 'Platform latihan coding gratis dengan mentoring dari komunitas. Tersedia 67 bahasa pemrograman dengan ribuan exercises.',
                'url'         => 'https://exercism.org',
                'category'    => 'programming',
                'level'       => 'intermediate',
                'views'       => 6700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'W3Schools — Web Development Tutorials',
                'description' => 'Referensi lengkap HTML, CSS, JavaScript, Python, SQL, dan teknologi web lainnya. Try it Yourself editor untuk praktik langsung.',
                'url'         => 'https://www.w3schools.com',
                'category'    => 'programming',
                'level'       => 'basic',
                'views'       => 14600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Full Stack Open — University of Helsinki',
                'description' => 'Kursus gratis React, Redux, Node.js, MongoDB, GraphQL, dan TypeScript dari University of Helsinki. Kurikulum modern web dev.',
                'url'         => 'https://fullstackopen.com/en',
                'category'    => 'programming',
                'level'       => 'intermediate',
                'views'       => 7800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Go by Example — Belajar Golang',
                'description' => 'Tutorial hands-on bahasa Go dengan contoh kode yang langsung bisa dijalankan. Dari Hello World sampai concurrency patterns.',
                'url'         => 'https://gobyexample.com',
                'category'    => 'programming',
                'level'       => 'intermediate',
                'views'       => 5200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1550063873-ab792950096b?w=600&h=400&fit=crop',
            ],

            // ===== DESIGN (10) =====
            [
                'title'       => 'Figma Learn — Design Fundamentals',
                'description' => 'Kursus resmi dari Figma untuk belajar design UI/UX dari dasar. Gratis dengan akun Figma. Include interactive exercises.',
                'url'         => 'https://www.figma.com/resources/learn-design',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 7640,
                'thumbnail'   => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Google UX Design Certificate (Coursera)',
                'description' => 'Sertifikat profesional UX Design dari Google di Coursera. Bisa audit gratis untuk akses materi tanpa sertifikat.',
                'url'         => 'https://www.coursera.org/professional-certificates/google-ux-design',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 11200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1586717799252-bd134f5c406a?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Dribbble Design Resources',
                'description' => 'Koleksi free design resources, mockups, icons, dan inspirasi dari komunitas desainer terbesar di dunia.',
                'url'         => 'https://dribbble.com/resources',
                'category'    => 'design',
                'level'       => 'intermediate',
                'views'       => 5430,
                'thumbnail'   => 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Coolors — Color Palette Generator',
                'description' => 'Tool gratis untuk generate color palette. Ekspor ke berbagai format, simpan koleksi, dan explore trending palettes.',
                'url'         => 'https://coolors.co',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 8100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Google Fonts — Free Web Fonts',
                'description' => 'Koleksi 1500+ font gratis dari Google. Cepat, mudah dipakai, dan bisa didownload untuk desain offline.',
                'url'         => 'https://fonts.google.com',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 9800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Unsplash — Free High-Resolution Photos',
                'description' => 'Library foto HD gratis untuk keperluan komersial dan personal. Lebih dari 3 juta foto berkualitas tinggi.',
                'url'         => 'https://unsplash.com',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 13500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Awwwards — Website Design Inspiration',
                'description' => 'Platform yang menampilkan website terbaik di dunia. Sumber inspirasi desain web, interaksi, dan animasi.',
                'url'         => 'https://www.awwwards.com',
                'category'    => 'design',
                'level'       => 'intermediate',
                'views'       => 6200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'SVG Repo — Free SVG Icons & Vectors',
                'description' => 'Koleksi 500.000+ ikon dan vektor SVG gratis. Download dan gunakan di project web, mobile, atau desain.',
                'url'         => 'https://www.svgrepo.com',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 7300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Design Course — YouTube Channel',
                'description' => 'Channel YouTube dengan tutorial desain UI/UX, web design, dan Figma. Konten berkualitas tinggi dan up-to-date.',
                'url'         => 'https://www.youtube.com/@DesignCourse',
                'category'    => 'design',
                'level'       => 'basic',
                'views'       => 5900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Material Design — Google Design System',
                'description' => 'Sistem desain dari Google. Panduan lengkap tentang komponen, warna, tipografi, dan motion untuk desain modern.',
                'url'         => 'https://m3.material.io',
                'category'    => 'design',
                'level'       => 'intermediate',
                'views'       => 8700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=600&h=400&fit=crop',
            ],

            // ===== ARTIFICIAL INTELLIGENCE (10) =====
            [
                'title'       => 'Fast.ai — Practical Deep Learning',
                'description' => 'Kursus deep learning gratis dan praktis. Pendekatan top-down learning yang langsung bisa diaplikasikan tanpa perlu PhD.',
                'url'         => 'https://www.fast.ai',
                'category'    => 'artificial-intelligence',
                'level'       => 'intermediate',
                'views'       => 13500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Google AI — Machine Learning Crash Course',
                'description' => 'Pengenalan machine learning dari Google. Interactive, gratis, dan mencakup TensorFlow exercises.',
                'url'         => 'https://developers.google.com/machine-learning/crash-course',
                'category'    => 'artificial-intelligence',
                'level'       => 'basic',
                'views'       => 10800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Hugging Face Course — NLP & Transformers',
                'description' => 'Kursus gratis tentang Natural Language Processing menggunakan library Transformers. Dari dasar tokenization sampai fine-tuning model.',
                'url'         => 'https://huggingface.co/course',
                'category'    => 'artificial-intelligence',
                'level'       => 'advanced',
                'views'       => 6200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Andrew Ng — Machine Learning (Stanford)',
                'description' => 'Kursus ML legendaris dari Prof. Andrew Ng di Coursera. Bisa audit gratis. Fondasi kuat untuk memahami algoritma ML.',
                'url'         => 'https://www.coursera.org/learn/machine-learning',
                'category'    => 'artificial-intelligence',
                'level'       => 'intermediate',
                'views'       => 16800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Kaggle Learn — Micro-Courses Machine Learning',
                'description' => 'Kursus singkat ML di Kaggle. Hands-on dengan notebook, dataset nyata, dan sertifikat gratis setelah selesai.',
                'url'         => 'https://www.kaggle.com/learn',
                'category'    => 'artificial-intelligence',
                'level'       => 'basic',
                'views'       => 9400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'OpenAI Cookbook — GPT & AI Recipes',
                'description' => 'Kumpulan contoh kode dan panduan menggunakan API OpenAI. Dari embeddings, function calling, sampai RAG patterns.',
                'url'         => 'https://cookbook.openai.com',
                'category'    => 'artificial-intelligence',
                'level'       => 'advanced',
                'views'       => 7600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1676299081847-824916de030a?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'DeepLearning.AI — Short Courses',
                'description' => 'Kursus pendek (1-2 jam) dari Andrew Ng tentang topik AI terkini: LangChain, ChatGPT, diffusion models, dan lainnya.',
                'url'         => 'https://www.deeplearning.ai/short-courses',
                'category'    => 'artificial-intelligence',
                'level'       => 'intermediate',
                'views'       => 8300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1680474569854-81216b34417a?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Papers With Code — ML Research & Code',
                'description' => 'Platform yang menghubungkan paper riset ML dengan implementasi kodenya. Lacak state-of-the-art di berbagai benchmark.',
                'url'         => 'https://paperswithcode.com',
                'category'    => 'artificial-intelligence',
                'level'       => 'advanced',
                'views'       => 5800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'TensorFlow Tutorials — Official',
                'description' => 'Tutorial resmi TensorFlow untuk deep learning. Dari basic classification sampai generative models dengan Colab notebooks.',
                'url'         => 'https://www.tensorflow.org/tutorials',
                'category'    => 'artificial-intelligence',
                'level'       => 'intermediate',
                'views'       => 7100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Elements of AI — University of Helsinki',
                'description' => 'Kursus pengantar AI gratis dari University of Helsinki. Pendekatan non-teknis yang cocok untuk semua kalangan.',
                'url'         => 'https://www.elementsofai.com',
                'category'    => 'artificial-intelligence',
                'level'       => 'basic',
                'views'       => 11200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=600&h=400&fit=crop',
            ],

            // ===== BUSINESS (10) =====
            [
                'title'       => 'Google Digital Garage — Digital Marketing',
                'description' => 'Kursus digital marketing gratis bersertifikat dari Google. 26 modul mencakup SEO, SEM, social media, dan analytics.',
                'url'         => 'https://learndigital.withgoogle.com/digitalgarage',
                'category'    => 'business',
                'level'       => 'basic',
                'views'       => 9300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Startup School by Y Combinator',
                'description' => 'Program gratis dari Y Combinator untuk belajar membangun startup. Include video lectures, resources, dan komunitas founder.',
                'url'         => 'https://www.startupschool.org',
                'category'    => 'business',
                'level'       => 'intermediate',
                'views'       => 7100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'HubSpot Academy — Inbound Marketing',
                'description' => 'Kursus dan sertifikasi gratis tentang inbound marketing, content marketing, dan sales. Sertifikat diakui industri.',
                'url'         => 'https://academy.hubspot.com',
                'category'    => 'business',
                'level'       => 'basic',
                'views'       => 8500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Google Analytics Academy',
                'description' => 'Pelajari Google Analytics 4 langsung dari Google. Kursus gratis bersertifikat tentang data analysis dan digital measurement.',
                'url'         => 'https://analytics.google.com/analytics/academy',
                'category'    => 'business',
                'level'       => 'intermediate',
                'views'       => 6400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Coursera — Financial Markets (Yale)',
                'description' => 'Kursus financial markets dari Prof. Robert Shiller (Yale). Pahami pasar keuangan, risk management, dan behavioral finance.',
                'url'         => 'https://www.coursera.org/learn/financial-markets-global',
                'category'    => 'business',
                'level'       => 'intermediate',
                'views'       => 5700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Shopify Learn — E-Commerce',
                'description' => 'Belajar e-commerce gratis dari Shopify. Panduan memulai toko online, marketing, dan branding untuk entrepreneur.',
                'url'         => 'https://www.shopify.com/learn',
                'category'    => 'business',
                'level'       => 'basic',
                'views'       => 7800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'edX — Entrepreneurship (MIT)',
                'description' => 'Kursus entrepreneurship dari MIT di edX. Belajar bagaimana membangun startup dari ide sampai peluncuran produk.',
                'url'         => 'https://www.edx.org/learn/entrepreneurship',
                'category'    => 'business',
                'level'       => 'intermediate',
                'views'       => 4900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Facebook Blueprint — Social Media Marketing',
                'description' => 'Kursus resmi Meta tentang iklan dan marketing di Facebook, Instagram, dan WhatsApp. Sertifikasi gratis tersedia.',
                'url'         => 'https://www.facebook.com/business/learn',
                'category'    => 'business',
                'level'       => 'basic',
                'views'       => 6100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Canva Design School — Business Projects',
                'description' => 'Tutorial desain untuk bisnis: presentasi, social media, branding, dan video marketing menggunakan Canva gratis.',
                'url'         => 'https://www.canva.com/designschool',
                'category'    => 'business',
                'level'       => 'basic',
                'views'       => 5300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Lean Startup — Eric Ries Methodology',
                'description' => 'Resource gratis tentang metodologi Lean Startup. Build-Measure-Learn loop, MVP, dan validated learning untuk founder.',
                'url'         => 'https://theleanstartup.com/principles',
                'category'    => 'business',
                'level'       => 'intermediate',
                'views'       => 4300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=600&h=400&fit=crop',
            ],

            // ===== BAHASA (10) =====
            [
                'title'       => 'Duolingo — Belajar Bahasa Gratis',
                'description' => 'Aplikasi belajar bahasa paling populer di dunia. Gratis, gamified, dan tersedia 40+ bahasa termasuk Jepang, Korea, dan Mandarin.',
                'url'         => 'https://www.duolingo.com',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 14200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'BBC Learning English',
                'description' => 'Resource belajar Bahasa Inggris gratis dari BBC. Video, podcast, grammar exercises, dan vocabulary builder.',
                'url'         => 'https://www.bbc.co.uk/learningenglish',
                'category'    => 'bahasa',
                'level'       => 'intermediate',
                'views'       => 6800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1543109740-4bdb38fda756?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Tae Kim — Guide to Learning Japanese',
                'description' => 'Panduan gratis belajar grammar Bahasa Jepang dari basic sampai advanced. Dianggap salah satu resource terbaik.',
                'url'         => 'https://guidetojapanese.org/learn',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 7500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Talk To Me In Korean (TTMIK)',
                'description' => 'Platform belajar Bahasa Korea gratis dengan podcast, video, dan textbook. Dari level 1 sampai 9.',
                'url'         => 'https://talktomeinkorean.com',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 8900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Deutsche Welle — Learn German',
                'description' => 'Kursus Bahasa Jerman gratis dari Deutsche Welle. Audio, video, dan interactive exercises dari A1 sampai C1.',
                'url'         => 'https://learngerman.dw.com',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 5400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1527866959252-deab85ef7d1b?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Busuu — Language Learning Community',
                'description' => 'Platform belajar bahasa dengan fitur community feedback dari native speakers. Kursus tersedia untuk 14 bahasa.',
                'url'         => 'https://www.busuu.com',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 6100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'LingQ — Read & Listen in Any Language',
                'description' => 'Belajar bahasa melalui membaca dan mendengar konten yang menarik. Import podcast, artikel, dan buku ke platform.',
                'url'         => 'https://www.lingq.com',
                'category'    => 'bahasa',
                'level'       => 'intermediate',
                'views'       => 4800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'IELTS Liz — Free IELTS Preparation',
                'description' => 'Website gratis untuk persiapan tes IELTS. Tips, model answers, vocabulary, dan practice tests dari mantan examiner.',
                'url'         => 'https://ieltsliz.com',
                'category'    => 'bahasa',
                'level'       => 'advanced',
                'views'       => 9200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Anki — Spaced Repetition Flashcards',
                'description' => 'Aplikasi flashcard gratis dengan spaced repetition system. Ideal untuk menghafal vocabulary bahasa asing dan kanji.',
                'url'         => 'https://apps.ankiweb.net',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 7100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'SpanishDict — Belajar Bahasa Spanyol',
                'description' => 'Kamus, grammar guide, dan kursus Bahasa Spanyol gratis. Conjugation tool dan pronunciation audio untuk setiap kata.',
                'url'         => 'https://www.spanishdict.com',
                'category'    => 'bahasa',
                'level'       => 'basic',
                'views'       => 5600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1489945052260-4f21c52571cc?w=600&h=400&fit=crop',
            ],

            // ===== MATEMATIKA (10) =====
            [
                'title'       => 'Khan Academy — Matematika & Sains',
                'description' => 'Platform belajar gratis dengan video penjelasan dan latihan soal. Dari aritmatika dasar sampai kalkulus dan statistik.',
                'url'         => 'https://www.khanacademy.org',
                'category'    => 'matematika',
                'level'       => 'basic',
                'views'       => 16500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=400&fit=crop',
            ],
            [
                'title'       => '3Blue1Brown — Essence of Linear Algebra',
                'description' => 'Seri video YouTube yang menjelaskan linear algebra dengan visualisasi yang indah dan intuitif. Wajib untuk mahasiswa STEM.',
                'url'         => 'https://www.3blue1brown.com/topics/linear-algebra',
                'category'    => 'matematika',
                'level'       => 'intermediate',
                'views'       => 8400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'MIT 18.06 — Linear Algebra (Gilbert Strang)',
                'description' => 'Kursus linear algebra legendaris dari Prof. Gilbert Strang MIT. Video lecture lengkap gratis di YouTube dan OCW.',
                'url'         => 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010',
                'category'    => 'matematika',
                'level'       => 'intermediate',
                'views'       => 7200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Desmos — Graphing Calculator Online',
                'description' => 'Kalkulator grafik online gratis yang powerful. Visualisasi fungsi, statistik, dan geometri secara interaktif.',
                'url'         => 'https://www.desmos.com/calculator',
                'category'    => 'matematika',
                'level'       => 'basic',
                'views'       => 10300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Wolfram Alpha — Computational Engine',
                'description' => 'Mesin komputasi yang bisa menyelesaikan soal matematika step-by-step. Dari aljabar, kalkulus, sampai differential equations.',
                'url'         => 'https://www.wolframalpha.com',
                'category'    => 'matematika',
                'level'       => 'intermediate',
                'views'       => 11800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Paul\'s Online Math Notes',
                'description' => 'Catatan matematika lengkap dari Prof. Paul Dawkins. Algebra, calculus I-III, dan differential equations dengan contoh soal.',
                'url'         => 'https://tutorial.math.lamar.edu',
                'category'    => 'matematika',
                'level'       => 'intermediate',
                'views'       => 5900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1580894742597-87bc8789db3d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Brilliant — Interactive STEM Learning',
                'description' => 'Platform belajar matematika dan sains secara interaktif. Beberapa kursus gratis tersedia untuk logic, algebra, dan geometry.',
                'url'         => 'https://brilliant.org',
                'category'    => 'matematika',
                'level'       => 'basic',
                'views'       => 8600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1453733190371-0a9bedd82893?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Mathway — Math Problem Solver',
                'description' => 'Tool gratis untuk menyelesaikan soal matematika. Ketik soal dan dapatkan jawaban step-by-step untuk algebra, calculus, dll.',
                'url'         => 'https://www.mathway.com',
                'category'    => 'matematika',
                'level'       => 'basic',
                'views'       => 9100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Professor Leonard — YouTube Calculus',
                'description' => 'Video lecture kalkulus lengkap di YouTube. Penjelasan sangat detail dan mudah dipahami. Favorit mahasiswa STEM.',
                'url'         => 'https://www.youtube.com/@ProfessorLeonard',
                'category'    => 'matematika',
                'level'       => 'intermediate',
                'views'       => 6700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'GeoGebra — Math Visualization',
                'description' => 'Tool gratis untuk visualisasi matematika: grafik, geometri, 3D plotting, statistik, dan kalkulus secara interaktif.',
                'url'         => 'https://www.geogebra.org',
                'category'    => 'matematika',
                'level'       => 'basic',
                'views'       => 7400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=400&fit=crop',
            ],

            // ===== TOOLS DEVELOPER (10) =====
            [
                'title'       => 'GitHub Student Developer Pack',
                'description' => 'Paket tools developer gratis untuk mahasiswa. Termasuk domain .me, JetBrains IDE, DigitalOcean $200, dan 100+ tools lainnya.',
                'url'         => 'https://education.github.com/pack',
                'category'    => 'tools-developer',
                'level'       => 'basic',
                'views'       => 19800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'DevDocs — All API Docs in One Place',
                'description' => 'Kumpulan dokumentasi API untuk developer. Offline support, fast search, dan mencakup 400+ bahasa pemrograman & framework.',
                'url'         => 'https://devdocs.io',
                'category'    => 'tools-developer',
                'level'       => 'intermediate',
                'views'       => 5600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Postman — API Development & Testing',
                'description' => 'Platform gratis untuk mendesain, test, dan dokumentasi API. Kolaborasi tim, mock servers, dan automated testing.',
                'url'         => 'https://www.postman.com',
                'category'    => 'tools-developer',
                'level'       => 'intermediate',
                'views'       => 8900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Vercel — Free Hosting & Deployment',
                'description' => 'Hosting gratis untuk frontend frameworks. Auto deploy dari Git, serverless functions, dan edge network global.',
                'url'         => 'https://vercel.com',
                'category'    => 'tools-developer',
                'level'       => 'basic',
                'views'       => 10200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Railway — Deploy Apps Easily',
                'description' => 'Platform deployment dengan free tier murah hati. Deploy backend, database, dan cron jobs dalam hitungan menit.',
                'url'         => 'https://railway.app',
                'category'    => 'tools-developer',
                'level'       => 'basic',
                'views'       => 6300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Regex101 — Regular Expression Tester',
                'description' => 'Tool online gratis untuk membangun dan menguji regex. Real-time matching, explanation, dan cheat sheet.',
                'url'         => 'https://regex101.com',
                'category'    => 'tools-developer',
                'level'       => 'intermediate',
                'views'       => 7400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'CodePen — Online Code Playground',
                'description' => 'Environment untuk menulis dan berbagi HTML, CSS, dan JavaScript secara online. Explore dan fork pen dari komunitas.',
                'url'         => 'https://codepen.io',
                'category'    => 'tools-developer',
                'level'       => 'basic',
                'views'       => 9800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Supabase — Open Source Firebase Alternative',
                'description' => 'Backend-as-a-Service open source. PostgreSQL, auth, storage, dan realtime subscriptions. Free tier sangat generous.',
                'url'         => 'https://supabase.com',
                'category'    => 'tools-developer',
                'level'       => 'intermediate',
                'views'       => 7800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Docker Hub — Container Registry',
                'description' => 'Registry terbesar untuk Docker container images. Temukan images official dan komunitas untuk development environment.',
                'url'         => 'https://hub.docker.com',
                'category'    => 'tools-developer',
                'level'       => 'advanced',
                'views'       => 6100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Can I Use — Browser Compatibility',
                'description' => 'Database browser support untuk fitur web (CSS, HTML, JS, SVG). Cek kompatibilitas sebelum menggunakan fitur baru.',
                'url'         => 'https://caniuse.com',
                'category'    => 'tools-developer',
                'level'       => 'basic',
                'views'       => 8300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
            ],

            // ===== REFERENSI AKADEMIK (10) =====
            [
                'title'       => 'MIT OpenCourseWare',
                'description' => 'Semua materi perkuliahan MIT tersedia gratis online. Ribuan kursus dari mathematics, engineering, sampai humanities.',
                'url'         => 'https://ocw.mit.edu',
                'category'    => 'referensi-akademik',
                'level'       => 'advanced',
                'views'       => 11700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Google Scholar — Pencarian Jurnal Ilmiah',
                'description' => 'Mesin pencari untuk literatur akademik. Temukan paper, thesis, jurnal, dan buku dari berbagai disiplin ilmu.',
                'url'         => 'https://scholar.google.com',
                'category'    => 'referensi-akademik',
                'level'       => 'intermediate',
                'views'       => 8900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'arXiv — Open-Access Research Papers',
                'description' => 'Repositori open-access terbesar untuk paper riset di bidang fisika, CS, matematika, dan AI. Gratis untuk semua.',
                'url'         => 'https://arxiv.org',
                'category'    => 'referensi-akademik',
                'level'       => 'advanced',
                'views'       => 7600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Sci-Hub — Access to Scientific Papers',
                'description' => 'Akses gratis ke jutaan paper ilmiah. Kontroversial tapi banyak digunakan peneliti di seluruh dunia.',
                'url'         => 'https://www.sci-hub.se',
                'category'    => 'referensi-akademik',
                'level'       => 'advanced',
                'views'       => 14200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Project Gutenberg — Free Ebooks',
                'description' => '70.000+ ebooks gratis dari karya-karya klasik. Download dalam format epub, kindle, dan HTML.',
                'url'         => 'https://www.gutenberg.org',
                'category'    => 'referensi-akademik',
                'level'       => 'basic',
                'views'       => 8100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'DOAJ — Directory of Open Access Journals',
                'description' => 'Direktori jurnal open access terkurasi. 19.000+ jurnal peer-reviewed dari seluruh bidang ilmu.',
                'url'         => 'https://doaj.org',
                'category'    => 'referensi-akademik',
                'level'       => 'intermediate',
                'views'       => 4700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1568667256549-094345857637?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'edX — University-Level Courses',
                'description' => 'Kursus online gratis dari Harvard, MIT, Berkeley, dan 160+ universitas top dunia. Audit gratis, sertifikat berbayar.',
                'url'         => 'https://www.edx.org',
                'category'    => 'referensi-akademik',
                'level'       => 'intermediate',
                'views'       => 9400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'OpenStax — Free Textbooks',
                'description' => 'Buku teks perguruan tinggi gratis yang peer-reviewed. Dari matematik, fisika, biologi, sampai ekonomi dan psikologi.',
                'url'         => 'https://openstax.org',
                'category'    => 'referensi-akademik',
                'level'       => 'basic',
                'views'       => 6800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Library Genesis (LibGen)',
                'description' => 'Database buku dan artikel ilmiah terbesar. Akses jutaan buku akademik dan paper secara gratis.',
                'url'         => 'https://libgen.is',
                'category'    => 'referensi-akademik',
                'level'       => 'advanced',
                'views'       => 12500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Coursera — Free Courses from Top Universities',
                'description' => 'Platform kursus online dari universitas terbaik. Audit gratis untuk akses materi video dan quiz tanpa sertifikat.',
                'url'         => 'https://www.coursera.org',
                'category'    => 'referensi-akademik',
                'level'       => 'intermediate',
                'views'       => 15600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&h=400&fit=crop',
            ],

            // ===== UI/UX (10) =====
            [
                'title'       => 'Laws of UX — Prinsip Desain UX',
                'description' => 'Kumpulan prinsip-prinsip UX yang berdasarkan riset psikologi. Referensi wajib untuk UI/UX designer.',
                'url'         => 'https://lawsofux.com',
                'category'    => 'ui-ux',
                'level'       => 'intermediate',
                'views'       => 7200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1586717799252-bd134f5c406a?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Mobbin — Mobile UI Design Patterns',
                'description' => 'Koleksi screenshot UI dari aplikasi mobile terbaik. Inspirasi desain dan referensi design patterns untuk mobile apps.',
                'url'         => 'https://mobbin.com',
                'category'    => 'ui-ux',
                'level'       => 'basic',
                'views'       => 5100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Nielsen Norman Group — UX Research',
                'description' => 'Artikel dan riset UX dari firma UX paling berpengaruh di dunia. Panduan evidence-based untuk keputusan desain.',
                'url'         => 'https://www.nngroup.com/articles',
                'category'    => 'ui-ux',
                'level'       => 'intermediate',
                'views'       => 6800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'UI Patterns — Design Pattern Library',
                'description' => 'Koleksi UI design patterns dengan contoh nyata. Referensi navigation, forms, data display, dan social patterns.',
                'url'         => 'https://ui-patterns.com',
                'category'    => 'ui-ux',
                'level'       => 'intermediate',
                'views'       => 4900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Maze — Free UX Research & Testing',
                'description' => 'Platform UX testing gratis untuk usability testing, prototype testing, dan user research. Integrasi dengan Figma.',
                'url'         => 'https://maze.co',
                'category'    => 'ui-ux',
                'level'       => 'intermediate',
                'views'       => 4300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1576153192396-180ecef2a715?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Refactoring UI — Design Tips',
                'description' => 'Tips praktis desain UI dari creator Tailwind CSS. Specific, actionable advice untuk improve interface tanpa design background.',
                'url'         => 'https://www.refactoringui.com',
                'category'    => 'ui-ux',
                'level'       => 'basic',
                'views'       => 8200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'UX Planet — Medium Publication',
                'description' => 'Publikasi Medium terbesar tentang UX design. Artikel dari ribuan designer tentang proses, tools, dan case studies.',
                'url'         => 'https://uxplanet.org',
                'category'    => 'ui-ux',
                'level'       => 'basic',
                'views'       => 5500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Checklist Design — UX Best Practices',
                'description' => 'Checklist untuk komponen UI umum: forms, buttons, cards, modals, dll. Pastikan desain kamu tidak melewatkan detail.',
                'url'         => 'https://www.checklist.design',
                'category'    => 'ui-ux',
                'level'       => 'basic',
                'views'       => 4100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1581291518633-83b4eef1d2fa?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Lottie Files — Free Animations',
                'description' => 'Koleksi animasi Lottie gratis untuk website dan mobile apps. JSON animations yang ringan dan smooth.',
                'url'         => 'https://lottiefiles.com',
                'category'    => 'ui-ux',
                'level'       => 'basic',
                'views'       => 7600,
                'thumbnail'   => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Penpot — Open Source Design Tool',
                'description' => 'Alternatif Figma yang open source dan gratis. Design, prototype, dan collaborate tanpa batasan. Self-hosted option.',
                'url'         => 'https://penpot.app',
                'category'    => 'ui-ux',
                'level'       => 'basic',
                'views'       => 5300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1558655146-364adaf1fcc9?w=600&h=400&fit=crop',
            ],

            // ===== CAREER (10) =====
            [
                'title'       => 'Tech Interview Handbook',
                'description' => 'Panduan lengkap untuk mempersiapkan technical interview. Resume tips, coding interview, system design, dan behavioral questions.',
                'url'         => 'https://www.techinterviewhandbook.org',
                'category'    => 'career',
                'level'       => 'intermediate',
                'views'       => 9500,
                'thumbnail'   => 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Roadmap.sh — Developer Roadmaps',
                'description' => 'Roadmap interaktif untuk berbagai path karir developer. Frontend, Backend, DevOps, AI, dan banyak lagi. Community-driven.',
                'url'         => 'https://roadmap.sh',
                'category'    => 'career',
                'level'       => 'basic',
                'views'       => 12300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'LeetCode — Coding Interview Practice',
                'description' => 'Platform #1 untuk latihan coding interview. 2800+ problems, discussion, dan mock interviews. Banyak konten gratis.',
                'url'         => 'https://leetcode.com',
                'category'    => 'career',
                'level'       => 'intermediate',
                'views'       => 15400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'NeetCode — DSA Roadmap & Solutions',
                'description' => 'Roadmap belajar Data Structures & Algorithms untuk coding interview. Video explanations dan curated problem lists.',
                'url'         => 'https://neetcode.io',
                'category'    => 'career',
                'level'       => 'intermediate',
                'views'       => 8700,
                'thumbnail'   => 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Indeed Career Guide',
                'description' => 'Panduan karir lengkap: tips resume, cover letter, interview preparation, salary negotiation, dan career development.',
                'url'         => 'https://www.indeed.com/career-advice',
                'category'    => 'career',
                'level'       => 'basic',
                'views'       => 7200,
                'thumbnail'   => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'LinkedIn Learning — Free Courses',
                'description' => 'Pilih kursus LinkedIn Learning gratis. Professional development, leadership, dan software skills dari expert instructors.',
                'url'         => 'https://www.linkedin.com/learning',
                'category'    => 'career',
                'level'       => 'basic',
                'views'       => 6400,
                'thumbnail'   => 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'System Design Primer — GitHub',
                'description' => 'Resource open-source untuk belajar system design. Wajib untuk persiapan senior engineer interview di FAANG companies.',
                'url'         => 'https://github.com/donnemartin/system-design-primer',
                'category'    => 'career',
                'level'       => 'advanced',
                'views'       => 11300,
                'thumbnail'   => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Glassdoor — Interview Questions & Reviews',
                'description' => 'Baca review perusahaan, gaji, dan pertanyaan interview dari karyawan asli. Persiapan interview yang lebih targeted.',
                'url'         => 'https://www.glassdoor.com',
                'category'    => 'career',
                'level'       => 'basic',
                'views'       => 8800,
                'thumbnail'   => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'Overleaf — LaTeX Resume Templates',
                'description' => 'Editor LaTeX online gratis dengan 100+ template resume profesional. Buat CV yang ATS-friendly dan stand out.',
                'url'         => 'https://www.overleaf.com/gallery/tagged/cv',
                'category'    => 'career',
                'level'       => 'basic',
                'views'       => 5900,
                'thumbnail'   => 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&h=400&fit=crop',
            ],
            [
                'title'       => 'HackerRank — Skills Certification',
                'description' => 'Platform coding challenges dengan sertifikasi skill gratis. Bisa ditampilkan di profil LinkedIn untuk attract recruiters.',
                'url'         => 'https://www.hackerrank.com',
                'category'    => 'career',
                'level'       => 'intermediate',
                'views'       => 10100,
                'thumbnail'   => 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&h=400&fit=crop',
            ],
        ];

        $categoryMap = Category::pluck('id', 'slug')->toArray();
        $allUsers = collect([$admin])->merge($users);

        foreach ($educations as $edu) {
            $categoryId = $categoryMap[$edu['category']] ?? null;
            if (!$categoryId) continue;

            $creator = $allUsers->random();

            Education::updateOrCreate(
                ['url' => $edu['url']],
                [
                    'title'       => $edu['title'],
                    'slug'        => Str::slug($edu['title']) . '-' . Str::random(5),
                    'description' => $edu['description'],
                    'url'         => $edu['url'],
                    'category_id' => $categoryId,
                    'level'       => $edu['level'],
                    'created_by'  => $creator->id,
                    'status'      => 'approved',
                    'views'       => $edu['views'],
                    'thumbnail'   => $edu['thumbnail'],
                ]
            );
        }
    }
}
